# Mapping of API routes to names in DB
ATTR_DICT = {
	'description-en': 'course_description_en',
	'description-fr': 'course_description_fr',
	'business-type': 'business_type_en',
	'type-de-livraison': 'business_type_fr',
	'provider': 'provider_en',
	'fournisseur': 'provider_fr',
	'displayed-on-gccampus': 'displayed_on_gccampus_en',
	'affiche-sur-gccampus': 'displayed_on_gccampus_fr',
	'duration': 'duration',
	'duree': 'duration',
	'main-topic': 'main_topic_en',
	'sujet-principal': 'main_topic_fr',
	'business-line': 'business_line_en',
	'ligne-d-affaires': 'business_line_fr',
	'required-training': 'required_training_en',
	'formation-requise': 'required_training_fr',
	'communities': 'communities_en',
	'communautes': 'communities_fr',
	'point-of-contact': 'point_of_contact',
	'point-de-contact': 'point_of_contact',
	'director': 'director',
	'directeur': 'director',
	'program-manager': 'program_manager',
	'gestionnaire-de-programme': 'program_manager',
	'project-lead': 'project_lead',
	'chef-de-projet': 'project_lead'
}
